version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: btd6_admin
      POSTGRES_PASSWORD: strongpassword1298
      POSTGRES_DB: btd6_leaderboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: